name: stallet_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.2.0
  stallet_lib:
    path: ../lib
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
